pipeline {
    agent any

    stages {

	stage('Установка зависимостей') {
            steps {
                script {
                    sh 'pip3 install pandas kaggle numpy scikit-learn matplotlib seaborn'
                }
            }
        }

        stage('Сбор данных') {
            steps {
                script {
                    sh 'python3 lab2/datacollection.py'
                }
            }
        }

        stage('Подготовка данных') {
            steps {
                script {
                    sh 'python3 lab2/data_preparation.py'
                }
            }
        }

        stage('Обучение модели') {
            steps {
                script {
                    sh 'python3 lab2/train_model.py'
                }
            }
        }

        stage('Оценка модели') {
            steps {
                script {
                    sh 'python3 lab2/evaluate_model.py'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'lab2/**/*.csv, lab2/**/*.pkl', allowEmptyArchive: true
        }
    }
}

